// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2a3FGQH25V5p4qfq4Dz3dFZO1NjH_IMA',
    appId: '1:687671524152:web:36b03793803ecf56269fcd',
    messagingSenderId: '687671524152',
    projectId: 'fir-calender-617ed',
    authDomain: 'fir-calender-617ed.firebaseapp.com',
    storageBucket: 'fir-calender-617ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD2RR9TQEkRseWNResZXmYKkJr6cVgwME',
    appId: '1:687671524152:android:9f745d0da80dc32b269fcd',
    messagingSenderId: '687671524152',
    projectId: 'fir-calender-617ed',
    storageBucket: 'fir-calender-617ed.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2a3FGQH25V5p4qfq4Dz3dFZO1NjH_IMA',
    appId: '1:687671524152:web:4b26130f540ad802269fcd',
    messagingSenderId: '687671524152',
    projectId: 'fir-calender-617ed',
    authDomain: 'fir-calender-617ed.firebaseapp.com',
    storageBucket: 'fir-calender-617ed.appspot.com',
  );

}